keys:
  # Users
  - &users:
    - &kristian age198e00r627fttqxts3qmdrvenc60uw6e468rpnp0eh9juprps6gcq2vgh5h
  # Hosts
  - &hosts:
    - &core age1702pt2jxuw9l63p2vc2pe4234yxym7557xfyr099s23drphvefds25w45h
    - &media age13qz09z677p7kags6mjzsjv9cea9l36wzdttrzqpsmj75jkdfcgyql3sumj
    - &builder age1kjl5ch4jaksd5d39z69hffztgyga9yg40lrfsz8wetrs8lz43emqflxpxh
#    - &public-1 age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#    - &public-2 age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#    - &dvr age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - &monitoring age1qm0rwtjpvfwkeannq0c0d22rj2qh5y7v402dnkexrtgrl8a89yxqftpkcn
    - &infrastructure age1czv6q0ppds2nnkqp2qry6r3arr92kp9l8h8snqq3hf3j002nqucsamepys
    - &zeus age17szadq780jpzlaw0qsfjggr7xvy80lgvul4kh9r7zud65cykzunswkthp5

creation_rules:
  - path_regex: hosts/core/secrets.ya?ml$
    key_groups:
    - age:
      - *core
      - *kristian

  - path_regex: hosts/media/secrets.ya?ml$
    key_groups:
    - age:
      - *media
      - *kristian

  - path_regex: hosts/builder/secrets.ya?ml$
    key_groups:
    - age:
      - *builder
      - *kristian

  - path_regex: hosts/infrastructure/secrets.ya?ml$
    key_groups:
    - age:
      - *infrastructure
      - *kristian

  - path_regex: hosts/public-1/secrets.ya?ml$
    key_groups:
    - age:
#      - *public-1
      - *kristian

  - path_regex: hosts/public-2/secrets.ya?ml$
    key_groups:
    - age:
#      - *public-2
      - *kristian

  - path_regex: hosts/dvr/secrets.ya?ml$
    key_groups:
    - age:
#      - *dvr
      - *kristian

  - path_regex: hosts/monitoring/secrets.ya?ml$
    key_groups:
    - age:
      - *monitoring
      - *kristian

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *core
      - *media
      - *builder
      - *infrastructure
#      - *public-1
#      - *public-2
#      - *dvr
      - *monitoring
      - *zeus
      - *kristian
  
  - path_regex: hosts/common/global/secrets.ya?ml$
    key_groups:
    - age:
      - *kristian