{
 "title": "Tailscale",
 "tags": [ "tailscale" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values({job=\"tailscale\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health Messages",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tailscaled_health_messages{job=\"tailscale\", instance=~\"$node\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Subnet Router",
   "type": "gauge",
   "description": "Advertised and approved subnet routes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tailscaled_advertised_routes{job=\"tailscale\", instance=~\"$node\"}",
     "legendFormat": "Advertised Routes"
    },
    {
     "expr": "tailscaled_approved_routes{job=\"tailscale\", instance=~\"$node\"}",
     "legendFormat": "Approved Routes"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Inbound/outbound bytes/sec per interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(tailscaled_inbound_bytes_total{job=\"tailscale\", instance=~\"$node\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}} recv {{path}}"
    },
    {
     "expr": "irate(tailscaled_outbound_bytes_total{job=\"tailscale\", instance=~\"$node\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}} trans {{path}}"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tailscaled_inbound_packets_total{job=\"tailscale\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}} recv {{path}}"
    },
    {
     "expr": "rate(tailscaled_outbound_packets_total{job=\"tailscale\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}} trans {{path}}"
    }
   ]
  },
  {
   "title": "Network Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tailscaled_inbound_dropped_packets_total{job=\"tailscale\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}} recv {{reason}}"
    },
    {
     "expr": "rate(tailscaled_outbound_dropped_packets_total{job=\"tailscale\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}} trans {{reason}}"
    }
   ]
  }
 ]
}