-- sonarr
GRANT CONNECT ON DATABASE "sonarr-main" TO sonarr;
GRANT CONNECT ON DATABASE "sonarr-log" TO sonarr;

\connect "sonarr-main"
GRANT ALL ON SCHEMA public TO sonarr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sonarr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sonarr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO sonarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO sonarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO sonarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO sonarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TYPES TO sonarr;

\connect "sonarr-log"
GRANT ALL ON SCHEMA public TO sonarr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sonarr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sonarr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO sonarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO sonarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO sonarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO sonarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TYPES TO sonarr;

-- radarr
\connect postgres

GRANT CONNECT ON DATABASE "radarr-main" TO radarr;
GRANT CONNECT ON DATABASE "radarr-log" TO radarr;

\connect "radarr-main"
GRANT ALL ON SCHEMA public TO radarr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO radarr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO radarr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO radarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO radarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO radarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO radarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TYPES TO radarr;

\connect "radarr-log"
GRANT ALL ON SCHEMA public TO radarr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO radarr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO radarr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO radarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO radarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO radarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO radarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TYPES TO radarr;

-- lidarr
\connect postgres

GRANT CONNECT ON DATABASE "lidarr-main" TO lidarr;
GRANT CONNECT ON DATABASE "lidarr-log" TO lidarr;

\connect "lidarr-main"
GRANT ALL ON SCHEMA public TO lidarr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO lidarr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO lidarr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO lidarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO lidarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO lidarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO lidarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TYPES TO lidarr;

\connect "lidarr-log"
GRANT ALL ON SCHEMA public TO lidarr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO lidarr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO lidarr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO lidarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO lidarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO lidarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO lidarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TYPES TO lidarr;

-- prowlarr
\connect postgres

GRANT CONNECT ON DATABASE "prowlarr-main" TO prowlarr;
GRANT CONNECT ON DATABASE "prowlarr-log" TO prowlarr;

\connect "prowlarr-main"
GRANT ALL ON SCHEMA public TO prowlarr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO prowlarr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO prowlarr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO prowlarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO prowlarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO prowlarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO prowlarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TYPES TO prowlarr;

\connect "prowlarr-log"
GRANT ALL ON SCHEMA public TO prowlarr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO prowlarr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO prowlarr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO prowlarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO prowlarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO prowlarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO prowlarr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TYPES TO prowlarr;